POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "joe doe",
    "email": "j@j.com"
}

###

POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "client 2",
    "email": "c2@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Content-Type: application/json

{
    "client_id": "3e2981ff-4197-4df4-a2bf-e8901479ea9e"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Content-Type: application/json

{
    "client_id": "bf2c8b8b-77c3-4384-a833-4eef9ce4326b"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Content-Type: application/json

{
    "account_id_from": "e76e5adc-9098-412e-8302-6fe0ab61e6ee",
    "account_id_to":"332477fd-d38c-4871-9053-89f8ddb28865",
    "amount": 50
}